/**
  ******************************************************************************
  * @file    mpu9250.c
  * @brief   MPU9250 IMU driver implementation.
  *
  * MIGRATION NOTE — STM32F411 → STM32H723ZG (Cortex-M7, 192 MHz)
  * ---------------------------------------------------------------
  * 1. HAL API (HAL_I2C_Mem_Read / HAL_I2C_Mem_Write):
  *    Identical signatures in both stm32f4xx_hal_i2c and stm32h7xx_hal_i2c.
  *    No changes required.
  *
  * 2. I2C peripheral register model:
  *    The F4 uses a CR1/CR2/CCR model; the H7 uses the new I2C_TIMINGR model.
  *    This is handled entirely inside MX_I2C1_Init() generated by CubeMX and
  *    is TRANSPARENT to the driver — no driver changes required.
  *
  * 3. L1 D-Cache coherency (CRITICAL for H7):
  *    The HAL I2C Mem_Read/Mem_Write functions used here are in POLLING mode
  *    (timeout-based, not DMA). In polling mode, data is transferred byte-by-byte
  *    under CPU control via the I2C FIFO/shift register. The CPU then writes the
  *    result directly into the destination buffer — bypassing DMA entirely.
  *    Therefore, D-Cache invalidation or SCB_CleanDCache_by_Addr is NOT required
  *    for polling-mode transfers.
  *
  *    IMPORTANT: If this driver is ever changed to DMA mode in the future,
  *    Rec_Data[] MUST be declared with __attribute__((aligned(32))) and placed
  *    in a non-cacheable SRAM region (e.g., D2 SRAM with MPU configured as
  *    Non-Cacheable), and SCB_CleanInvalidateDCache_by_Addr() called accordingly.
  *
  * 4. Timing / HAL_Delay:
  *    HAL_Delay() is driven by SysTick (1 ms period), which is always correctly
  *    configured by HAL_Init() regardless of CPU clock. No changes required.
  *
  * 5. FPU:
  *    The Cortex-M7 has a double-precision FPU. All float arithmetic in this
  *    file uses single-precision (float / 'f' suffix literals), which maps to
  *    the hardware FPU. No changes required.
  ******************************************************************************
  */

#include "mpu9250.h"
#include <math.h>

/* --------------------------------------------------------------------------
 * I2C Device Address
 * The MPU9250 7-bit address is 0x68 (AD0=LOW). The STM32 HAL expects the
 * 8-bit left-shifted form: 0x68 << 1 = 0xD0.
 * -------------------------------------------------------------------------- */
#define MPU9250_ADDR     0xD0U

/* --------------------------------------------------------------------------
 * MPU9250 Register Map
 * -------------------------------------------------------------------------- */
#define SMPLRT_DIV_REG   0x19U  /* Sample Rate Divider                        */
#define GYRO_CONFIG_REG  0x1BU  /* Gyroscope Configuration                    */
#define ACCEL_CONFIG_REG 0x1CU  /* Accelerometer Configuration                */
#define ACCEL_XOUT_H_REG 0x3BU  /* Accelerometer Measurements (start)         */
#define TEMP_OUT_H_REG   0x41U  /* Temperature Measurement                    */
#define GYRO_XOUT_H_REG  0x43U  /* Gyroscope Measurements (start)             */
#define PWR_MGMT_1_REG   0x6BU  /* Power Management 1                         */
#define WHO_AM_I_REG     0x75U  /* Device Identity                            */

/* --------------------------------------------------------------------------
 * Sensor Full-Scale Range (FSR) Scale Factors
 * Gyro:  ±500 °/s  → LSB sensitivity = 65.5 LSB/(°/s)
 * Accel: ±2 g      → LSB sensitivity = 16384 LSB/g
 * -------------------------------------------------------------------------- */
static const float GYRO_SCALE  = 65.5f;
static const float ACCEL_SCALE = 16384.0f;

/* --------------------------------------------------------------------------
 * MPU9250_Init
 * -------------------------------------------------------------------------- */
void MPU9250_Init(I2C_HandleTypeDef *I2Cx)
{
    uint8_t check;
    uint8_t Data;

    /* Verify WHO_AM_I: MPU9250 returns 0x71 (rev A/B) or 0x73 (rev C) */
    HAL_I2C_Mem_Read(I2Cx, MPU9250_ADDR, WHO_AM_I_REG, I2C_MEMADD_SIZE_8BIT,
                     &check, 1U, 1000U);

    if (check == 0x71U || check == 0x73U)
    {
        /* Wake the device: clear SLEEP bit in PWR_MGMT_1 */
        Data = 0x00U;
        HAL_I2C_Mem_Write(I2Cx, MPU9250_ADDR, PWR_MGMT_1_REG, I2C_MEMADD_SIZE_8BIT,
                          &Data, 1U, 1000U);

        /* Sample Rate Divider: SMPLRT_DIV = 7 → Sample Rate = 1 kHz / (1 + 7) = 125 Hz */
        Data = 0x07U;
        HAL_I2C_Mem_Write(I2Cx, MPU9250_ADDR, SMPLRT_DIV_REG, I2C_MEMADD_SIZE_8BIT,
                          &Data, 1U, 1000U);

        /* Gyroscope Configuration: FS_SEL = 1 → ±500 °/s */
        Data = 0x08U;
        HAL_I2C_Mem_Write(I2Cx, MPU9250_ADDR, GYRO_CONFIG_REG, I2C_MEMADD_SIZE_8BIT,
                          &Data, 1U, 1000U);

        /* Accelerometer Configuration: AFS_SEL = 0 → ±2 g */
        Data = 0x00U;
        HAL_I2C_Mem_Write(I2Cx, MPU9250_ADDR, ACCEL_CONFIG_REG, I2C_MEMADD_SIZE_8BIT,
                          &Data, 1U, 1000U);
    }
}

/* --------------------------------------------------------------------------
 * MPU9250_Read_Accel_Gyro
 *
 * H7 Cache Note: This function uses a stack-local buffer (Rec_Data[14]).
 * Since HAL I2C is in POLLING mode (CPU-driven, no DMA), the D-Cache does
 * NOT cause coherency issues. The CPU reads/writes the buffer directly.
 * -------------------------------------------------------------------------- */
uint8_t MPU9250_Read_Accel_Gyro(I2C_HandleTypeDef *I2Cx, MPU9250_t *DataStruct)
{
    uint8_t  Rec_Data[14];
    int16_t  Accel_X_RAW, Accel_Y_RAW, Accel_Z_RAW;
    int16_t  Gyro_X_RAW,  Gyro_Y_RAW,  Gyro_Z_RAW;

    /*
     * Burst-read 14 bytes beginning at ACCEL_XOUT_H (0x3B):
     *   [0..5]  = Accel X/Y/Z high+low bytes
     *   [6..7]  = Temperature high+low (unused)
     *   [8..13] = Gyro X/Y/Z high+low bytes
     */
    if (HAL_I2C_Mem_Read(I2Cx, MPU9250_ADDR, ACCEL_XOUT_H_REG,
                         I2C_MEMADD_SIZE_8BIT, Rec_Data, 14U, 100U) == HAL_OK)
    {
        /* Reconstruct signed 16-bit raw values */
        Accel_X_RAW = (int16_t)((Rec_Data[0]  << 8) | Rec_Data[1]);
        Accel_Y_RAW = (int16_t)((Rec_Data[2]  << 8) | Rec_Data[3]);
        Accel_Z_RAW = (int16_t)((Rec_Data[4]  << 8) | Rec_Data[5]);

        Gyro_X_RAW  = (int16_t)((Rec_Data[8]  << 8) | Rec_Data[9]);
        Gyro_Y_RAW  = (int16_t)((Rec_Data[10] << 8) | Rec_Data[11]);
        Gyro_Z_RAW  = (int16_t)((Rec_Data[12] << 8) | Rec_Data[13]);

        /* Scale to physical units */
        DataStruct->Accel_X = (float)Accel_X_RAW / ACCEL_SCALE;
        DataStruct->Accel_Y = (float)Accel_Y_RAW / ACCEL_SCALE;
        DataStruct->Accel_Z = (float)Accel_Z_RAW / ACCEL_SCALE;

        /* Apply gyroscope DC-bias offsets computed during calibration */
        DataStruct->Gyro_X = ((float)Gyro_X_RAW / GYRO_SCALE) - DataStruct->Gyro_X_Offset;
        DataStruct->Gyro_Y = ((float)Gyro_Y_RAW / GYRO_SCALE) - DataStruct->Gyro_Y_Offset;
        DataStruct->Gyro_Z = ((float)Gyro_Z_RAW / GYRO_SCALE) - DataStruct->Gyro_Z_Offset;

        return 1U; /* Success */
    }

    return 0U; /* I2C error */
}

/* --------------------------------------------------------------------------
 * MPU9250_Calculate_Angles
 *
 * Implements a Euler-kinematics complementary filter.
 * All trig uses single-precision variants (sinf/cosf/atan2f/sqrtf/tanf)
 * which are correctly mapped to the Cortex-M7 hardware FPU.
 * -------------------------------------------------------------------------- */
void MPU9250_Calculate_Angles(MPU9250_t *DataStruct, float dt)
{
    float ax = DataStruct->Accel_X;
    float ay = DataStruct->Accel_Y;
    float az = DataStruct->Accel_Z;

    /* --- Accelerometer reference angles --- */
    float accel_roll  = atan2f(ay, az) * 180.0f / 3.14159265f;
    float accel_pitch = atan2f(-ax, sqrtf(ay * ay + az * az)) * 180.0f / 3.14159265f;

    /* --- Gyroscope deadband (noise gate: 1 °/s) --- */
    const float threshold = 1.0f;
    float gx = DataStruct->Gyro_X;
    float gy = DataStruct->Gyro_Y;
    float gz = DataStruct->Gyro_Z;

    if (gx > -threshold && gx < threshold) { gx = 0.0f; }
    if (gy > -threshold && gy < threshold) { gy = 0.0f; }
    if (gz > -threshold && gz < threshold) { gz = 0.0f; }

    /* --- Euler kinematic transformation (body-frame → world-frame) ---
     * Prevents yaw drift when sensor is tilted (avoids gimbal lock coupling).
     */
    float roll_rad  = DataStruct->Roll  * 3.14159265f / 180.0f;
    float pitch_rad = DataStruct->Pitch * 3.14159265f / 180.0f;

    float sin_roll  = sinf(roll_rad);
    float cos_roll  = cosf(roll_rad);
    float tan_pitch = tanf(pitch_rad);
    float cos_pitch = cosf(pitch_rad);

    /* Guard against division-by-zero near ±90° pitch (gimbal lock) */
    if (cos_pitch > -0.01f && cos_pitch < 0.0f)  { cos_pitch = -0.01f; }
    if (cos_pitch >= 0.0f  && cos_pitch < 0.01f) { cos_pitch =  0.01f; }

    float roll_rate  = gx + gy * sin_roll * tan_pitch + gz * cos_roll * tan_pitch;
    float pitch_rate = gy * cos_roll - gz * sin_roll;
    float yaw_rate   = (gy * sin_roll + gz * cos_roll) / cos_pitch;

    /* --- Complementary filter (α = 0.96) --- */
    const float alpha = 0.96f;
    DataStruct->Roll  = alpha * (DataStruct->Roll  + roll_rate  * dt) + (1.0f - alpha) * accel_roll;
    DataStruct->Pitch = alpha * (DataStruct->Pitch + pitch_rate * dt) + (1.0f - alpha) * accel_pitch;

    /* Yaw is gyro-only (no magnetometer) */
    DataStruct->Yaw = DataStruct->Yaw + yaw_rate * dt;
}

/* --------------------------------------------------------------------------
 * MPU9250_Calibrate
 *
 * Collects 200 static samples to estimate gyroscope DC bias offsets.
 * HAL_Delay(3) between samples is SysTick-based and works identically
 * on H7 regardless of CPU clock speed.
 * -------------------------------------------------------------------------- */
void MPU9250_Calibrate(I2C_HandleTypeDef *I2Cx, MPU9250_t *DataStruct)
{
    const uint16_t NUM_SAMPLES = 200U;
    float gyro_x_sum = 0.0f;
    float gyro_y_sum = 0.0f;
    float gyro_z_sum = 0.0f;

    /* Clear offsets so raw bias is captured, not corrected values */
    DataStruct->Gyro_X_Offset = 0.0f;
    DataStruct->Gyro_Y_Offset = 0.0f;
    DataStruct->Gyro_Z_Offset = 0.0f;

    for (uint16_t i = 0U; i < NUM_SAMPLES; i++)
    {
        MPU9250_Read_Accel_Gyro(I2Cx, DataStruct);
        gyro_x_sum += DataStruct->Gyro_X;
        gyro_y_sum += DataStruct->Gyro_Y;
        gyro_z_sum += DataStruct->Gyro_Z;
        HAL_Delay(3U); /* ~3 ms between samples → total ≈ 600 ms */
    }

    DataStruct->Gyro_X_Offset = gyro_x_sum / (float)NUM_SAMPLES;
    DataStruct->Gyro_Y_Offset = gyro_y_sum / (float)NUM_SAMPLES;
    DataStruct->Gyro_Z_Offset = gyro_z_sum / (float)NUM_SAMPLES;
}
